In [2]:
import pandas as pd
Customers=pd.read_excel("customers(clean).xlsx")
Products=pd.read_excel("products(clean).xlsx")
Orders=pd.read_excel("orders(clean).xlsx")

,order_id,customer_id,product_id,order_date,quantity,discount_pct,total_amount,payment_method,shipping_city,shipping_state,delivery_days,marketing_channel,is_returning_customer,review_rating,return_flag
0,ORD000001,CUST00544,PROD0001,2024-12-23,4,0,1341.08,Apple Pay,MACity3,MA,6,Social Media,1,2,0
1,ORD000002,CUST00954,PROD0002,2023-05-02,5,25,103.80,Gift Card,CACity3,CA,5,Direct,1,2,0
2,ORD000003,CUST02898,PROD0003,2024-01-04,5,0,235.75,Credit Card,WACity3,WA,9,Organic Search,1,4,0
3,ORD000004,CUST02697,PROD0004,2023-05-21,1,5,134.05,PayPal,OHCity1,OH,14,Social Media,1,5,0
4,ORD000005,CUST02413,PROD0005,2022-05-31,3,20,531.17,Credit Card,FLCity1,FL,14,Organic Search,0,4,0

In [4]:
Products.head()

  product_id    product_name product_category  unit_price
0   PROD0001       Bed Frame        Furniture      335.27
1   PROD0002          Puzzle             Toys       27.68
2   PROD0003    Office Chair        Furniture       47.15
3   PROD0004       Bookshelf        Furniture      141.11
4   PROD0005  Organic Coffee          Grocery      221.32

In [5]:
Customers.head()

  customer_id signup_date  customer_age customer_gender state
0   CUST00544  2024-03-26            21           Other    MA
1   CUST00954  2022-01-27            56          Female    CA
2   CUST02898  2023-07-30            70           Other    WA
3   CUST02697  2022-01-27            23            Male    OH
4   CUST02413  2022-05-08            62            Male    FL

In [6]:
Orders.head()

,order_id,customer_id,product_id,order_date,quantity,discount_pct,total_amount,payment_method,shipping_city,shipping_state,delivery_days,marketing_channel,is_returning_customer,review_rating,return_flag
0,ORD000001,CUST00544,PROD0001,2024-12-23,4,0,1341.08,Apple Pay,MACity3,MA,6,Social Media,1,2,0
1,ORD000002,CUST00954,PROD0002,2023-05-02,5,25,103.80,Gift Card,CACity3,CA,5,Direct,1,2,0
2,ORD000003,CUST02898,PROD0003,2024-01-04,5,0,235.75,Credit Card,WACity3,WA,9,Organic Search,1,4,0
3,ORD000004,CUST02697,PROD0004,2023-05-21,1,5,134.05,PayPal,OHCity1,OH,14,Social Media,1,5,0
4,ORD000005,CUST02413,PROD0005,2022-05-31,3,20,531.17,Credit Card,FLCity1,FL,14,Organic Search,0,4,0

In [ ]:
==============EDA====================

In [7]:
#Customers Analysis
# Who are the top customers?
customer_sales = Orders.groupby('customer_id')['total_amount'].sum().sort_values(ascending=False)

customer_sales.head(10)

customer_id
CUST02218    11184.57
CUST00292    10854.47
CUST01013    10525.59
CUST00851    10393.52
CUST01201    10351.03
CUST00963    10348.08
CUST02729    10317.53
CUST02234    10162.26
CUST01163    10113.04
CUST02191    10012.15
Name: total_amount, dtype: float64

In [ ]:
# How many customers are repeat customers?
Orders['is_returning_customer'].value_counts()

In [ ]:
#Customer spending distribution
customer_spending = Orders.groupby('customer_id')['total_amount'].sum()

In [ ]:
#Customer age analysis
Customers['customer_age'].describe()

In [ ]:
#Product Analysis
#Best-selling products
product_data.groupby('product_name')['quantity'].sum().sort_values(ascending=False).head(10)

In [ ]:
#Highest revenue products
product_data.groupby('product_name')['total_amount'].sum().sort_values(ascending=False).head(10)

In [ ]:
#Category performance
product_data.groupby('product_category').agg(
    Revenue=('total_amount', 'sum'),
    Quantity=('quantity', 'sum'),
    Orders=('order_id', 'nunique')
).sort_values('Revenue', ascending=False)

In [ ]:
#Sales by state
Orders.groupby('shipping_state')['total_amount'].sum().sort_values(ascending=False)

In [ ]:
#Orders by state
Orders.groupby('shipping_state')['order_id'].nunique().sort_values(ascending=False)

In [ ]:
#Average order value by state
Orders.groupby('shipping_state')['total_amount'].mean().sort_values(ascending=False)

In [ ]:
#Average rating
Orders['review_rating'].mean()

In [ ]:
#Returns by product category
product_data.groupby('product_category')['return_flag'].mean() * 100

In [ ]:
#Payment Method Analysis
#which payment most popular
Orders.groupby('payment_method').agg(
    Orders=('order_id', 'count'),
    Revenue=('total_amount', 'sum'),
    AOV=('total_amount', 'mean')
)